# Generated by Django 3.1.4 on 2020-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
