# Generated by Django 3.1.4 on 2020-12-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_auto_20201205_1944")]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="quantity", new_name="stock"
        )
    ]
